/*
 * Helpers for things that walk and inspect the AST generated by the parser.
 */
package com.x1010data.intellik.psi.impl;

import com.intellij.lang.ASTNode;
import com.x1010data.intellik.psi.KItem;
import com.x1010data.intellik.psi.KTypes;

public class KPsiImpUtil {
    public static String getKey(KItem el) {
        ASTNode idNode = el.getNode().findChildByType(KTypes.IDENT);
        return idNode == null ? null : idNode.getText();
    }
}
